### ISSUE TITLE
Handle errors - invalid newdle/participant codes

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#103]
Currently the client-side app just blows up if one of those codes are invalid. We should rather show a proper error message / 404 page.

**Comment by ThiefMaster** [comment]
For an invalid participant code we could show a nice error, with the option to switch to anonymous mode instead.

**Comment by pferreir** [comment]
*Empty noddle bowl*

**Comment by ThiefMaster** [comment]
Can we have a cracked noodle bowl image for unexpected errors? :D
