### ISSUE TITLE
Display timezone in the answer page

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#127]
We do not currently display it. It could be either close to the calendar on the side (maybe above?) or even inside the white box in the header.

![image](https://user-images.githubusercontent.com/2699/67391299-b150a100-f59e-11e9-9494-8ebef994f686.png)

**Please provide a screenshot along with the PR.**

**Comment by Anilpandiya** [comment]
@pferreir i can work on this.

**Comment by pferreir** [comment]
Thanks @Anilpandiya. It should be a pretty straightforward task. Please test your code carefully before sending the PR. If you have any questions, feel free to pop by IRC/Matrix.

**Comment by pferreir** [comment]
Hi @Anilpandiya,
In the end are you gonna work on this one?

**Comment by ThiefMaster** [comment]
@Anilpandiya How is it going? If you need any help feel free to ask here or in our [IRC channel](https://webchat.freenode.net/#indico). If you don't end up working on it it's OK as well, but please let us know so we can unassign the issue again.

**Comment by Anilpandiya** [comment]
Won't able to work on this.

**Comment by glehmannmiotto** [comment]
The ability to view/set/choose a time zone would be very useful for international meetings

**Comment by ThiefMaster** [comment]
this was done in #218, and there's #224 for display improvements
