### ISSUE TITLE
Integration with Indico

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#128]
This can only be done once we have an endpoint on the Indico side that can receive the data and forward the user to the event creation dialog.

**Comment by ThiefMaster** [comment]
Including a list of participants is rather tricky: newdle uses just a "name" and the email is not available for anyone who wasn't logged in. But in Indico participants always need a first name, last name and email.

Maybe we could just pre-populate the event creation dialog with the date and time?

**Comment by adl1995** [comment]
@ThiefMaster - So for this task we need to somehow export the event from Newdle to Indico? Is the endpoint @pferreir referring to now available, or does it need to be implemented first? I could only find the endpoint for fetching an event: https://docs.getindico.io/en/stable/http_api/exporters/event/

Also, for the first name, last name and email requirement on Indico, I guess we can just prompt the user to add additional details if they want to export it to Indico.

**Comment by ThiefMaster** [comment]
No, we do not have anything on the Indico side yet - I would probably keep this issue for later and try to find something else first...

**Comment by prolineserver** [comment]
Wouldn't the other way around make more sense: You set up a meeting in Indico without fixed date yet, and instead refer to a newdle poll?

**Comment by ThiefMaster** [comment]
Indico does not support events without a date/time and doing so would be **much** more complex.

**Comment by prolineserver** [comment]
Yes, unfortunately. We sometimes set a dummy date, but yes it is more an Indico feature request.
