### ISSUE TITLE
Add confirmation step to "e-mail participants"

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#135]
It's quite easy to press it by mistake. A possible solution would be a confirmation modal.
We should also clarify in that dialog:
 * how many participants will receive an e-mail (so that the user can understand how much spam they will generate);
 * whether any of the participants (and how many) do not have an e-mail address (and possible also list them) - those are the "unknown" participants who were added ad-hoc.

![image](https://user-images.githubusercontent.com/2699/67393512-d515e600-f5a2-11e9-967a-5ca6241cce52.png)

**Comment by ThiefMaster** [comment]
> whether any of the participants  do not have an e-mail address

we already have that ;)

but I think we really need an actual participant list (also on the page where you decide on a final date), maybe even showing whether they've already been emailed or not.

**Comment by pferreir** [comment]
> but I think we really need an actual participant list

Indeed.

**Comment by hannahshort** [comment]
Happy to take this

**Comment by ThiefMaster** [comment]
sure, go for it! do you want to go "all the way", i.e. also start storing which participants have been notified and adding a participant list (as discussed in the previous comments)?

if not, we can open a separate issue for it and keep this one limited to just adding a confirmation prompt for the current functionality we already have
