### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#137]
Even better, an animated GIF like we've got [in Indico](https://github.com/indico/indico#indico----)!

**Comment by Anilpandiya** [comment]
@pferreir  I can work on this. Provide screenshot and position where it needs to be attach in readme

**Comment by pferreir** [comment]
Hi @Anilpandiya. Taking the screenshot/GIF is actually part of the task. It should be one of the first things in the README, see Indico's example to see what I mean.

**Comment by rpanczer** [comment]
@pferreir I can add a GIF in quick

**Comment by pferreir** [comment]
@rpanczer thanks! Since @Anilpandiya stopped answering 5 days ago, I am assigning this to you. Thanks for the PR!

**Comment by ThiefMaster** [comment]
closed in #154
