### ISSUE TITLE
Optionally notify newdle creator when a new answer comes in

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#141]
This could exist in the form of a on option that is set in Step 3:

![image](https://user-images.githubusercontent.com/2699/67484365-42d81580-f668-11e9-9268-235ae31776d1.png)

(a switch/checkbox, something like "keep me notified about new answers", which could be turned on by default). It could also be modifiable from the newdle summary page.

**Comment by alcalaperez** [comment]
@ThiefMaster

**Comment by alcalaperez** [comment]
I'm on it (again)

**Comment by alcalaperez** [comment]
![UI](https://user-images.githubusercontent.com/9081709/93086263-276a6480-f697-11ea-85d4-65c5d8c629d8.png)

UI set
