### ISSUE TITLE
Attach iCalendar file (*.ics) to result e-mail

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#143]
The result e-mail is currently very simple and it would be great if we could send an `*.ics` file along with it, so that people can just add the new meeting to their calendars. Integration with Indico will make this unnecessary in organizations using it, but it's still a nice thing to have in places where Indico is not an option.

![image](https://user-images.githubusercontent.com/2699/67489947-b8e17a00-f672-11e9-81c9-db6c28a86c32.png)

**Comment by Tarektouati** [comment]
i'll do it can you assign me to it

**Comment by ThiefMaster** [comment]
sure, there you go!

**Comment by ThiefMaster** [comment]
@Tarektouati How is it going? If you need any help feel free to ask here or in our [IRC channel](https://webchat.freenode.net/#indico).

**Comment by Tarektouati** [comment]
@ThiefMaster  Hey ! still working on the issue , i'll open PR soon, i'll have a look to the IRC channel if got stuck !

**Comment by saibot94** [comment]
Could I have a stab at this one? Just to clarify, this requires just attaching the `.ics` file to the generated mail, right?

**Comment by ThiefMaster** [comment]
Yes indeed. You can probably use a library like [icalendar](https://pypi.org/project/icalendar) to generate it.
