### ISSUE TITLE
Replace react-circular-progressbar with something nicer that can show all three states

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#151]
We are currently using `react-circular-progressbar` to show how many people are available on the summary page (in the [ParticipantTable](https://github.com/indico/newdle/blob/89815bc8adb9f52e260e31ec81109adf752c686f/newdle/client/src/components/ParticipantTable.js#L80-L91) component):

![image](https://user-images.githubusercontent.com/179599/67604136-16f98480-f77b-11e9-8bab-5e67052a09f2.png)

The library's rendering is not amazing - you can see some red on the outer edges of the green bar. Also, we have a third state in addition to available/unavailable, which is "if need be". The library does not support multiple states.

Instead of what we have now, it should:

- look clean (no weird colored "border")
- support all 3 states (red/yellow/green)

You can either find a library (nothing huge like D3, which is 250kb minified!) that does this, or add a new react component for it that generates the SVG itself.

**Comment by rpanczer** [comment]
@ThiefMaster I can help out with this one

**Comment by ThiefMaster** [comment]
@rpanczer that would be great! Let me know if you have any questions (either here or in our [IRC channel](https://webchat.freenode.net/#indico) - it's late night here though so replies may soon take a while)

**Comment by rpanczer** [comment]
@ThiefMaster Made the component, just can't get `newdle` started to test. I ran `MAKE` on the repo, then started the dev servers. I received an error `(RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.)` when trying to login.

**Comment by ThiefMaster** [comment]
strange, check newdle/newdle.cfg - it should have an autogenerated key. if not, just set it to some random string

**Comment by rpanczer** [comment]
Ah I tried this but then problem just jumps down the file to `OIDC_AUTHORIZE_URL` being `None`.  
I am on a Mac. Would you be able to share an example config?

Here is my config file:
https://gist.github.com/rpanczer/986580952747459c01c380084a79f182

**Comment by ThiefMaster** [comment]
`SKIP_LOGIN = True` and you can ignore everything else :)

**Comment by rpanczer** [comment]
https://github.com/indico/newdle/pull/153
