### ISSUE TITLE
Example configuration file for accessing the rest of the application

### ISSUE THREAD

**Issue by nop33** [indico/newdle#152]
How do I need to configure my `newdle/newdle.cfg` file in order to be able to "Get started >". After following the instructions of the readme file (`make`,  `make flask-server` and `make react-server`) I am able to load the home page, but not much more. Is there an example configuration that I can use so that I can access the rest of the pages of the application?

**Comment by ThiefMaster** [comment]
You just need to set a random `SECRET_KEY` and `SKIP_LOGIN = True` (so you don't need an openid-connect server for authentication).

The makefile is actually supposed to [update the config](https://github.com/indico/newdle/blob/master/Makefile#L46-L48), but it might not work properly on MacOS...

**Comment by nop33** [comment]
Perfect, thank you!
