### ISSUE TITLE
Answer page: highlight currently selected day

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#158]
Right now the currently selected day in the calendar is not highlighted on the right side. This can create confusion when using the arrows and the calendar to navigate. We should somehow indicate the "active" day, even if it doesn't have many consequences in pretty much anything else.

![image](https://user-images.githubusercontent.com/2699/67753192-a1b8d880-fa34-11e9-8425-8965671c7b4a.png)

**Comment by VirtualEvan** [comment]
I will take this one
