### ISSUE TITLE
Add (python) tests for API functions that aren't covered yet

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#160]
`api_test.py` has already a bunch of tests, but not all API functions are covered yet.

Missing ones:

- [x] `get_busy_times` - mock `_get_busy_times`; just ensure it requires authentication
- [ ] `get_participant_busy_times` - same here, but cover the logic that checks whether it will return busy times or fail with an error
- [x] `get_my_newdles` - make sure that it does not return participant codes in the response
- [x] `update_newdle`
- [x] `get_participant_me`
- [x] `create_unknown_participant`
- [x] `create_participant`
- [ ] `send_result_emails` - use the `mail_queue` fixture to check that emails are sent

To skip for now:

- `users` - makes more sense once we have pluggable user directories

---

Note: Especially if you are an external contributor, feel free to add just some of the tests listed above. You do not need to send a big PR adding tests for everything (but you are of course welcome to do so if you'd like)

**Comment by pablostellet** [comment]
Hi @ThiefMaster,
Can I help on this task? :)

**Comment by ThiefMaster** [comment]
Sure! If you want to work on any specific test please mention it in here in case someone else wants to work on it as well to avoid two people doing the same.

**Comment by pablostellet** [comment]
Alright, I will run the project first then pick one and say here 😄

**Comment by ThiefMaster** [comment]
@pablostellet Are you still going to work on this?

While there's nothing wrong with deciding to not contribute, it would be nice to at least leave a comment in such a case!

**Comment by tomasr8** [comment]
I'd like to give this one a try ;)

**Comment by pjseweryn** [comment]
Hi, I would like to help with this task as well, in particular with send_result_emails case as agreed with tomasr8.

**Comment by ThiefMaster** [comment]
Hey, as long as you don't both work on the exact same test individually (ie duplicate work for no benefit) or actually work together I'm perfectly fine with that!

**Comment by Biboba** [comment]
I guess that one can be closed ?
- ```get_participant_busy_times``` was solved in https://github.com/indico/newdle/pull/255
- ```send_result_emails``` was solved in https://github.com/indico/newdle/pull/259
