### ISSUE TITLE
Allow participants to see summary

### ISSUE THREAD

**Issue by hannahshort** [indico/newdle#174]
It would be really useful if there were an option for participants to see the summary of choices, as well as the survey owner. I'm using Newdle as follows:

- I make survey with 0 users
- Share link with mailing list
- People complete their availabilities

I used to share Doodles and people would try and change their availability (i.e. reschedule meetings) if there were one choice that was clearly the winner (or if an important person could only make a specific slot).

**Comment by mariadimou** [comment]
I support this request. I use newdle for meetings of the Academic Training Committee, CDA members and various projects, involving experiments. Participants select slots where people important to them can join. If they can't see when another VIP participant is available to come, they can't choose.
Thanks
M
