### ISSUE TITLE
Delete newdles after a time

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#179]
Newdles are something ephemeral; there's no need for long-term archival.

We should delete them after a certain time, and maybe indicate when they will happen (at least to the creator) when viewing it.

Also need to decide when to start counting against the deadline... some options:

- final date
- date when the newdle was finalized
- latest option in the newdle
- date when the newdle was created (probably not a good idea depending on how long in the future the available options are)

Also, what to do with unfinalized newdles? Delete them some time after the date of the latest choice?

**Comment by ThiefMaster** [comment]
No need to add a background task scheduler like celery for this BTW. If we implement this as a flask cli command we can create a scheduled job on openshift that runs it every day or so.

**Comment by saibot94** [comment]
Could I start looking into this one? We just need to fully establish what kind of behavior we want.

I'd propose:

- **final newdles**: delete them after a configurable amount of time
-  **incomplete newdles**:
    - alter the DB and store the creation date of the newdle, delete it after some other amount of time if they're not completed
    - delete after the date of the latest choice. The only issue I see here is when there aren't any choices done.

**Comment by ThiefMaster** [comment]
Summarizing what we discussed on Mattermost:

- two new settings (good luck finding names), one for the lifetime after the final date (if chosen), one for the lifetime after the last activity. defaults: 3M after last activity, 1M after after final date. we probably do not need more granularity than months.
- last activity gets set on creation and updated whenever someone answers, or the newdle is finalized
- newdles get deleted only if both criteria are met, so if i finalize a newdle taking place in 12M, it'd be deleted after 13M (with the defaeults)

**Comment by saibot94** [comment]
So the settings will be in the `newdle.cfg` file with the others, meaning the cleanup command won't have any arguments, correct?

**Comment by ThiefMaster** [comment]
yes, i think it makes sense to have it in the config file - that way we could display it in the UI as well
