### ISSUE TITLE
Add meeting of more than 1,5h 

### ISSUE THREAD

**Issue by JesperCERN** [indico/newdle#186]
Hi, 
It would be useful to be able to add time slots of more than 1,5h. Maybe a "more" button could expand to allow for unlimited time slots?

**Comment by mjc42** [comment]
Hello. +1 on this one -- this alone blocks me from adopting Newdle. Perhaps to generalise the suggestion: it is fine to supply a list of standard/default meeting lengths, but please allow the user to specify an arbitrary meeting length in hours and minutes (perhaps up to a limit of 24h).

Follow-up suggestion: while creating a poll, if the poll already contains a meeting of length X, offer X among the default/standard options (e.g. in the drop-down) when adding another meeting slot in the same poll. (If the user already made one 3h slot, chances are good that the next 19 slots will also be of length 3h...)

**Comment by ThiefMaster** [comment]
Slots always have the same duration anyway - you cannot have slots with different lengths in the same newdle.

But I agree that custom longer durations make perfect sense.
