### ISSUE TITLE
Clarify participants vs link, early in the creation steps

### ISSUE THREAD

**Issue by Axel-Naumann** [indico/newdle#187]
Hi,

Thanks for Newdle!

Could you state, on the "Choose the participants", that *alternatively* and additionally, participants can be invited through a link? That's essential information - that entering participants is not a required step. It currently says "can be added later", but that's not the same as "you don't have to specify any participants; you can also just share a link."

It's also unclear whether I as the person setting up the Newdle is a participant automatically. I'd recommend to add the current user automatically to the list of participants.

Thanks!

Axel.

**Comment by lgatting** [comment]
Can I be assigned to this task? I have only marginal experience with React, but it seems doable.

**Comment by ThiefMaster** [comment]
Sure, I think this i just about adding text anyway!
