### ISSUE TITLE
Time definition could be streamlined

### ISSUE THREAD

**Issue by Axel-Naumann** [indico/newdle#188]
Hi,

In addition to https://github.com/indico/newdle/issues/183 (esp the "bulk time slot" option) I'd like to suggest the following:

When entering the digits for a meeting time, the default value (for me) is `10:00 AM`.
- If I enter "15" into the hour field, it gets "autocorrected" to `03:00 AM`. It would be even better if it got autocorrected to `03:00 PM` :-)
- Once I've entered a slot at 15:00 - sorry, "03:00 PM" ;-) - it again shows `10:00 AM` as the default value for the next slot. I think it would be a big usability improvement if the next default would be end-of-the-previous-slot if that exists. I.e. for the last slot being 15:00-15:30, suggest 15:30 as default value for a new slot to be added.

Cheers, Axel.

**Comment by ThiefMaster** [comment]
We're using a standard HTML5 time field, so your first suggestion is impossible to implement without using something custom (which we should probably do!). Too bad browser vendors did not take this usecase into account, it would be much smarter to convert values >12 to PM...

Keeping the earliest previous time as the default sounds like a very good idea though! Maybe we can even be smart and pick the earliest time from a previous day that does not have an entry yet on the day where you are adding the new time slot...
