### ISSUE TITLE
Improve the newdle results overview

### ISSUE THREAD

**Issue by plourenco** [indico/newdle#190]
When evaluating the pool, having a tabular view, for example, (ideally with the option to rearrange the order in which respondents appear) could become more useful than a static list.

**Comment by iokasti** [comment]
I would like to work on this part!

**Comment by iokasti** [comment]
![Screenshot_2020-09-21 Summary aaaa · newdle](https://user-images.githubusercontent.com/20352699/93774716-d53ebb80-fc21-11ea-884a-1afdef256330.png)
![Screenshot_2020-09-21 Summary aaaa · newdle(1)](https://user-images.githubusercontent.com/20352699/93774725-d7a11580-fc21-11ea-9759-3fc4555b3c72.png)

Is this what's expected as an extension to the results overview page? Do you suggest any correction?

**Comment by ThiefMaster** [comment]
Looks nice! I guess the placement of the switch is just there for testing and not final?

Since we have more space here for the participants, I'd show their avatar like we do in other places.

How does it look like if there are many timeslots (let's say 20+)? Probably `overflow-x:auto` on the table would be the best option

**Comment by iokasti** [comment]
![Screenshot_2020-09-22 Summary asas · newdle(2)](https://user-images.githubusercontent.com/20352699/93901972-5a47d480-fcf7-11ea-9703-ef9e56033b34.png)

So, I've modified the switch position, added the users' avatars and applied the suggested adjustments for the table to cover the overflow cases.

![Screenshot_2020-09-22 Summary eree · newdle](https://user-images.githubusercontent.com/20352699/93902437-d3472c00-fcf7-11ea-92a9-c640b73528a5.png)

Here's also an example of the icons based on user availability.
What do you think?

**Comment by ThiefMaster** [comment]
To save vertical space I'd probably put the avatar next to the name. Besides that I like it :)

**Comment by iokasti** [comment]
I've noticed that, given a rather long user name both tables won't respond well. I did try to manipulate the given css but didn't manage eventually to offer a solution. Do you have any suggestions on that matter? Is this indeed an issue of concern?

**Comment by ThiefMaster** [comment]
`text-overflow: ellipsis` usually works well

**Comment by iokasti** [comment]
That's one of the additions that I've tried but didn't seem to work.
