### ISSUE TITLE
Improve rendering on a smartphone

### ISSUE THREAD

**Issue by andreypz** [indico/newdle#196]
A poll on a smartphone looks pretty ugly at the moment.
[snapshot](https://slack-files.com/T7ZH0UM5F-F018SFS696C-777818c409)

**Comment by ThiefMaster** [comment]
You are right, this looks awful. I realized that a few times myself when opening an invitation on the phone...

We already have an issue to improve this, and we soon do another newdle sprint where this is VERY likely to be improved. :)
