### ISSUE TITLE
Component: Participant

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#20]
This is a row in the timeline showing name, avatar and availability of a participant.

![image](https://user-images.githubusercontent.com/2699/62291300-e51a9f80-b463-11e9-9196-f996850a5215.png)

**Comment by mic4ael** [comment]
I did something similar to that in  https://github.com/indico/newdle/pull/25/files#diff-d90753d40345487768e866c868a618af (at least the avatar part ;))

**Comment by mic4ael** [comment]
So maybe I would wait until this PR gets merged and then customize the existing component according to our requirements ;)

**Comment by meluru** [comment]
Yes, I agree, that's the best way. : )
