### ISSUE TITLE
Display options in local timezone

### ISSUE THREAD

**Issue by hannahshort** [indico/newdle#208]
It would be helpful for international recipients to see the Newdle slot options displayed in their local timezone.

---

It looks like we can nowadays get the current timezone from the browser (we do not have a "user profile" yet where such a thing could be stored, and people may answer as guests anyway) via [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat), so ideally we'd default to that timezone, but the user should be able to change it (this could also be done in a second step).

It should also be clear to the user that they are seeing it in their own timezone, maybe with an option to view it in the default timezone as chosen by the newdle creator.

An important case to take into account is that the start *date* may be different in the user's timezone - we have to be careful that we still submit it correctly for the original slot (ie time zone conversion should be purely a display thing).

Slightly tricky part: `getCalendarDates` (possibly other selectors as well, but on a quick glance I only found this one - best to eventually test it) are used both to fetch free-busy information from the API (always needs to use the raw value without timezone conversion) and to display the dates in the calendar (which would need to be adjusted using the user's timezone).

**Comment by ThiefMaster** [comment]
related: #127

**Comment by Diego-Zulu** [comment]
Hi there! I would like to work on this issue

I've been going through the code, and I believe I should be able to do it by refactoring the functions that end up applying the `.format` function on a moment object. If I apply the timezone to the moment object before formatting, I should be able to get the correct way of printing the dates

I'll reach out if I have any questions or problems!

**Comment by ThiefMaster** [comment]
Great! 👍 
In this task we only need it on the main "answer newdle" page, i.e. the page on `/newdle/XXX` ([example](https://newdle.cern.ch/newdle/jJvWYRSm)). Adding it on the summary page would be a good second step (separate issue+pr) especially now that the summary is also visible to participants, but no need to add more work to this particular issue!

I think we don't send the newdle's timezone back to the client yet, so you'll have to include it when returning the newdle data from the API.

For the client-side implementation my approach would probably involve selectors and combining selectors (createSelector) (so you get the data from one selector, and the newdle's timezone from another selector, and then doing some "timezone magic" in your new selector).

I would in fact start with these two things so newdle can show the answer page and timeslots in the client's timezone.
Even if submission (or showing previously-selected values in case of someone already having answered) likely doesn't work yet, that's probably already a good point to open a draft PR.
