### ISSUE TITLE
Add docker-compose.yml and instructions for Docker deployment

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#215]
There is already a Dockerfile, but it would be great to provide a way for people to quickly test the system.

**Comment by carantunes** [comment]
Would like to do this one  ✋

**Comment by ThiefMaster** [comment]
sure, go for it! please keep it separate from the Dockerfile that's already in place as this one is actually used for the current openshift deployment (maybe in a subdirectory?)

**Comment by pferreir** [comment]
I don't think we need a new Dockerfile, just a `docker-compose.yml`. At most we could parametrize the file with some ARGs, if we really need it.
