### ISSUE TITLE
Bottommost slots on answer page don't render at correct position

### ISSUE THREAD

**Issue by Diego-Zulu** [indico/newdle#221]
I have noticed that slots have a slight shift in positioning the closer they are to the bottom of the timeline. Here's an example:
<img width="1219" alt="Screen Shot 2020-09-05 at 19 44 57" src="https://user-images.githubusercontent.com/21281337/92314612-8f8ebb80-efb0-11ea-8c43-c6f75d801ead.png">
23:30 appears just to the right of 24. To my understanding, this slot should have started a little higher, right?

I quickly debugged it and it seems to be related to the fact that the timeline overflows a little bit from the Grid Row, although please dig into more detail when finding a solution

**Comment by pferreir** [comment]
Indeed, there's something wrong there. Thanks for reporting!

**Comment by asieraguado** [comment]
I could take this one.
