### ISSUE TITLE
Add GitHub action to automatically comment with the SQL for alembic revisions

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#238]
This action should check if a PR adds new Alembic revisions. If that's the case, it should run `flask db upgrade --sql PREV:LATEST` with `LATEST` being the `revision` of the last revision and `PREV` being the `down_revision` of the first revision added in the PR and comment on the PR with something like this:

    This PR contains database changes. Before merging it, make sure to apply the migration in production:
    
    ```sql
    <sql here>
    ```

    When reviewing the PR, make sure that the changes will not break the previously deployed
    version, i.e. any new column needs to have a `server_default` or be nullable.

**Comment by saibot94** [comment]
I'd like to try this one out, thanks!
