### ISSUE TITLE
Nicer e-mails

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#241]
The e-mails which are currently sent are too sho... concise and rather ugl... minimalistic. Having something a little bit more professional (e.g. adding a footer, making the text seem a little bit friendlier) would already help. Ideally, a nice header/buttons like you see in mails sent from commercial/professional apps would be nice.

**Comment by Caetan95** [comment]
I was looking how to do it and I think I can do it. Maybe a good idea is to base the design like the Mattermost email notification are

**Comment by Caetan95** [comment]
Something like this? 
![Newdle_mail_notification](https://user-images.githubusercontent.com/71437950/93850466-770bea00-fcae-11ea-95d9-6b5dc4290460.png)

**Comment by pferreir** [comment]
It looks very nice, but a few comments:
  * Maybe we can omit the "Mr/Ms" since anyway it's not relevant
  * I would remove CERN from the footer since the app can be installed elsewhere
  * I'd remove the Indico logo
  * The background color should be more newdle-y 😉

**Comment by ThiefMaster** [comment]
- also, copyright in an email footer isn't really useful ;)
- I'm missing the name of the recipient

btw I'd attach the images to the email so it doesn't rely on loading external content OR make sure it still looks good in mail clients not loading external images

**Comment by pferreir** [comment]
> also, copyright in an email footer isn't really useful ;)
it's not a copyright sign, it's an @

**Comment by ThiefMaster** [comment]
ah yeah indeed, didn't notice it on the small phone screen :D

anyway, do we need a footer at all? think the email looks pretty great with out it (maybe better?)...
or maybe just a very simple one with "This email was sent by newdleI" or something like that?

**Comment by Caetan95** [comment]
![Newdle_mail_notification v2](https://user-images.githubusercontent.com/71437950/93885122-14354580-fce4-11ea-8d57-baf9d0c9d363.png)

This is the new version. The problem of putting the recipient name is that this var is not stored, so I can not get it.

**Comment by ThiefMaster** [comment]
when calling `notify_newdle_participants` you can include it in the `lambda p: {...}` dict and then have access to it in the template

**Comment by ThiefMaster** [comment]
I find the "newdle is a tool developed ..." line still a bit unnecessary...

And I'd link "newdle" (lowercase n) in "This email was sent by newdle" to the URL of the newdle instance that sent the email

**Comment by hannahshort** [comment]
For language, I'd suggest the following to make it sound a bit more natural: 

```
Hi, <name>! You have a fresh newdle.

Guinea Pig would like you to help them choose a time for the event "..."

Respond by using your personal link or the button below.
```

And the button could be, ``Go to newdle``

**Comment by ThiefMaster** [comment]
What do others think about the "fresh newdle"? Sounds a bit strange to me ;x

**Comment by hannahshort** [comment]
I thought it was quite funny. (But not "you have fresh newdle" with a grammar mistake as that sounds a bit racist...)

**Comment by pferreir** [comment]
> What do others think about the "fresh newdle"? Sounds a bit strange to me ;x

I concur with @hannahshort.

**Comment by Caetan95** [comment]
@hannahshort thanks for the help 😄 the absence of the letter 'a' in the sentence was a typographical error, sorry. @ThiefMaster I put it as a funny metaphor, I can change it if you want

**Comment by ThiefMaster** [comment]
I don't have strong opinion on it :) if the others think it's good i don't mind keeping it (in the grammatically-correct form ofc)

**Comment by ThiefMaster** [comment]
Please rebase to the latest master; I just merged #237 which adds a new email (when someone replies to a newdle) so this should be made pretty as well.

Since we have two different HTML mails which probably both use the same basic structure and styling I would recommend to add a `base_email.html` template with a block for the content and `{% extends 'base_email.html' %}` from it in the individual email templates.

**Comment by Caetan95** [comment]
![Newdle_mail_notification v3](https://user-images.githubusercontent.com/71437950/94115670-59738780-fe4a-11ea-90a0-f156ccaab8f1.png)

Here is it the new version. If the design is okay I can also change the result_mail.html based on the base_email.html that it is received once the creator chooses the final date

**Comment by Caetan95** [comment]
- Result mail once the creator has chosen the final date ![Newdle_result_mail_notification](https://user-images.githubusercontent.com/71437950/94160857-5ea1f800-fe85-11ea-85b1-f6efa44725c2.png)

- Reply mail for the creator when a participant chooses a date(s). Different screenshots depending on the selection made
![Newdle_reply_full_mail_notification](https://user-images.githubusercontent.com/71437950/94161012-8729f200-fe85-11ea-8629-902f0ca8c08c.png)

![Newdle_reply_semifull_mail_notification](https://user-images.githubusercontent.com/71437950/94161203-bb9dae00-fe85-11ea-8434-711cb9743ab5.png)

![Newdle_reply_uff_mail_notification](https://user-images.githubusercontent.com/71437950/94161219-bfc9cb80-fe85-11ea-909a-8469d5971847.png)

![Newdle_reply_noup_mail_notification](https://user-images.githubusercontent.com/71437950/94161230-c22c2580-fe85-11ea-8115-72c72bd0459c.png)

**Comment by ThiefMaster** [comment]
- Not sure if italic+underscore isn't a bit much (any other opinions?)
- if "this link or the button below" do the same, I would remove that line altogether and maybe just keep the button?

**Comment by Leats** [comment]
>     * Not sure if italic+underscore isn't a bit much (any other opinions?)
I agree! I'd probably test both separately to see what's better!

>     * if "this link or the button below" do the same, I would remove that line altogether and maybe just keep the button?
I think that's a good idea!

Also, I'd probably change the background color from this light blue to just white, that would also make the newdle logo pop more :)

**Comment by Caetan95** [comment]
Changes done. Let me know if it is ok :slightly_smiling_face: 

Invitation email:
![Newdle_invitation_mail_notification v4](https://user-images.githubusercontent.com/71437950/94397513-491e1e00-0164-11eb-8ed6-35e26f69301e.png)

Reply email:
![Newdle_reply_uff_mail_notification v2](https://user-images.githubusercontent.com/71437950/94397532-576c3a00-0164-11eb-8967-ed35ece8cf29.png)

Result email:
![Newdle_result_mail_notification v2](https://user-images.githubusercontent.com/71437950/94397542-5d621b00-0164-11eb-8c54-8cb40711e47d.png)

**Comment by Caetan95** [comment]
Should I make a PR or should I change something else before?

**Comment by ThiefMaster** [comment]
I'd go ahead with the PR. We can always make/suggest some small changes later!
