### ISSUE TITLE
Step 3 - Finalize newdle

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#26]
At this point we should ask the user for the event's title. We should also tell the user that the participants will receive an e-mail once they confirm the creation.

`POST /api/newdle` should be called with the filled in info (also from the previous steps) and then the page should change slightly to reflect that fact that the newdle has been created.

![image](https://user-images.githubusercontent.com/2699/62468441-62148480-b796-11e9-94bf-83764543d31e.png)
![image](https://user-images.githubusercontent.com/2699/62468457-6771cf00-b796-11e9-9149-3a483d5adcf3.png)

**Comment by ThiefMaster** [comment]
Redirect should be client-side though - API calls doing a redirect are kind of weird.

**Comment by pferreir** [comment]
Sure

**Comment by pferreir** [comment]
> Redirect should be client-side though - API calls doing a redirect are kind of weird.

Sure. Actually, I've removed the part about the redirect shortly after. Maybe you read only the email notification?

**Comment by ThiefMaster** [comment]
Yeah true, I didn't read the text again after following the link
