### ISSUE TITLE
Add i18n: TopHeader

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#286]
We'd like to make the newdle frontend i18n-capable.
This issue is about adding i18n support to the `TopHeader` component (usually this is in a file with the same name).

Please test your changes, especially if you update a string that needs pluralization (we did not add pluralization so far because we didn't have i18n and doing it without an i18n library is not pretty).

Useful resources:

- The project's [README](https://github.com/indico/newdle#readme) explains how to run newdle
- **[Here's an example PR](https://github.com/indico/newdle/pull/267/files) where we added i18n to some components.** It contains [React usage](https://github.com/indico/newdle/pull/267/files#diff-0cc54461cea891fa78c0e85c7d6df434R172) (`<Trans>`), [string usage](https://github.com/indico/newdle/pull/267/files#diff-e5661acb3a7ba762bb8141855a9ccf73R191) (template literal tagged with `t`) and [pluralization](https://github.com/indico/newdle/pull/267/files#diff-0cc54461cea891fa78c0e85c7d6df434R153-R157).
- There's also the [Lingui documentation](https://js-lingui-git-next.lingui-js.now.sh/) but be aware that this is not fully up to date for the version we are using (Lingui 3)
- We do not use artificial IDs (like `newdle.created.message`); the source strings are always the English version
- When adding the lingui-related import (from `'@lingui/macro'`) make sure to put this import before any relative `./something` imports
- You do not need to update any .po files manually; you can run `make i18n` or simply `git commit` - we have a pre-commit hook which automatically updates the po file and stages it to be committed as well.

In case the component in this issue is rather small, feel free to take care of multiple components in a single PR. Don't forget to add `closes #xxx, closes #yyy` to your PR so all relevant issues are closed.

Thanks in advance for making a useful contribution during this [Hacktoberfest](https://hacktoberfest.digitalocean.com/)! 🎉

**Comment by matincodes** [comment]
hello, would love to work on this

**Comment by subhashissuara** [comment]
@ThiefMaster I was gonna take this but the only possible change it in `alt="Newdle logo"` out of which I am assuming Newdle shouldn't be translated, so only logo is left. Here is the sneak peak.

```
    <header className={styles.header}>
      <Grid columns={2}>
        <Grid.Row verticalAlign="middle">
          <Grid.Column>
            <Header as="h1" className={styles.title}>
              <Link to="/">
                <Image src={logo} alt="Newdle logo" />
              </Link>
            </Header>
          </Grid.Column>
          <Grid.Column textAlign="right">
            <UserMenu />
          </Grid.Column>
        </Grid.Row>
        <Grid.Row>
          <Grid.Column tablet={1} computer={4} />
          <Grid.Column mobile={16} tablet={14} computer={8}>
            <Switch>
              <Route exact path="/" component={HomeHeader} />
              <Route exact path="/new" component={CreationHeader} />
              <Route exact path="/newdle/:code/summary" component={SummaryHeader} />
              <Route exact path="/newdle/:code/:partcode?" component={AnswerHeader} />
            </Switch>
          </Grid.Column>
          <Grid.Column tablet={1} computer={8} />
        </Grid.Row>
      </Grid>
    </header>
```

**Comment by ThiefMaster** [comment]
> the only possible change in it seems like `alt="Newdle logo"`

You are right, and I was actually thinking the same. I think it would make sense to translate it, since "logo" is probably not the same in every language. BTW, can you please replace the source text there with `newdle logo` instead of `Newdle logo` since "newdle" should always be written in lowercase?

**Comment by subhashissuara** [comment]
Ahh, that makes sense! Yes, I have changed to lowercase. Thank you so much!
