### ISSUE TITLE
Add i18n: UserSearchResults

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#291]
We'd like to make the newdle frontend i18n-capable.
This issue is about adding i18n support to the `UserSearchResults` component (usually this is in a file with the same name).

Please test your changes, especially if you update a string that needs pluralization (we did not add pluralization so far because we didn't have i18n and doing it without an i18n library is not pretty).

Useful resources:

- The project's [README](https://github.com/indico/newdle#readme) explains how to run newdle
- **[Here's an example PR](https://github.com/indico/newdle/pull/267/files) where we added i18n to some components.** It contains [React usage](https://github.com/indico/newdle/pull/267/files#diff-0cc54461cea891fa78c0e85c7d6df434R172) (`<Trans>`), [string usage](https://github.com/indico/newdle/pull/267/files#diff-e5661acb3a7ba762bb8141855a9ccf73R191) (template literal tagged with `t`) and [pluralization](https://github.com/indico/newdle/pull/267/files#diff-0cc54461cea891fa78c0e85c7d6df434R153-R157).
- There's also the [Lingui documentation](https://js-lingui-git-next.lingui-js.now.sh/) but be aware that this is not fully up to date for the version we are using (Lingui 3)
- We do not use artificial IDs (like `newdle.created.message`); the source strings are always the English version
- When adding the lingui-related import (from `'@lingui/macro'`) make sure to put this import before any relative `./something` imports
- You do not need to update any .po files manually; you can run `make i18n` or simply `git commit` - we have a pre-commit hook which automatically updates the po file and stages it to be committed as well.

In case the component in this issue is rather small, feel free to take care of multiple components in a single PR. Don't forget to add `closes #xxx, closes #yyy` to your PR so all relevant issues are closed.

Thanks in advance for making a useful contribution during this [Hacktoberfest](https://hacktoberfest.digitalocean.com/)! 🎉

**Comment by linhhvo** [comment]
Hi @ThiefMaster, can I work on this?

**Comment by ThiefMaster** [comment]
Hi, sure!

Before submitting your PR please make sure that the linters pass (`make format` should fix most things, and you can use `make lint` to check locally).

**Comment by linhhvo** [comment]
Hi @ThiefMaster, I am trying to run `make` to run newdle but it doesn't recognize the command. I'm using Windows so do I have to do something differently or am I missing something here?

**Comment by ThiefMaster** [comment]
Ah, if you are on Windows 10 you could use WSL to get a Linux environment. If you don't want to do that but have everything else ready feel free to just send the PR; the linters run in CI anyway (I'll just need to generate the po file manually..)
