### ISSUE TITLE
Switching to "View Summary" view resets the answers

### ISSUE THREAD

**Issue by avivace** [indico/newdle#309]
If have selected the answers but not submitted them, and click on "View summary" on the top, the answers get reset without any warning.

![image](https://user-images.githubusercontent.com/14352721/95084684-7fd4d500-071e-11eb-883e-121424e3bde1.png)

**Comment by ThiefMaster** [comment]
Maybe we can use the `<UnloadPrompt />` component on this page? PR welcome :)

**Comment by Caetan95** [comment]
I can do it. Just an alert when changing view _"Are you sure you want to leave this page without saving?"_?

**Comment by ThiefMaster** [comment]
Yes, that's what `UnloadPrompt` does ;)
