### ISSUE TITLE
Some timeslots near the end of the day look weird

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#328]
![image](https://user-images.githubusercontent.com/179599/97928944-57191d00-1d68-11eb-8032-88bdbe3e3990.png)

IIRC. it's normal that they are truncated in order to avoid making the page much larger, but a timeslot that lasts longer should not appear to be shorter than the other one!

**Comment by mic4ael** [comment]
Hey! I would be happy to take a look into this issue :) Is it up for grabs?

**Comment by ThiefMaster** [comment]
sure!
