### ISSUE TITLE
Compilation failure on docker-dev-run

### ISSUE THREAD

**Issue by yarons** [indico/newdle#340]
I'm trying to run `make docker-dev-run` on macOS Catalina 10.15.6

First I'm seeing this message (Which I'm not sure relevant to the case):

    make: python3.8: Command not found

And then:
```
react-server    | ./src/util/i18n.js
react-server    | Module not found: Can't resolve '../locales/en/messages' in '/newdle/client/src/util'

```
And same goes for the Web UI on 127.0.0.1:3000
<img width="586" alt="Screen Shot 2021-03-03 at 18 20 18" src="https://user-images.githubusercontent.com/406826/109836770-31841d80-7c4d-11eb-90f0-bd849d3c98a7.png">

I've already checked locales/en and there's no messages.po in it (There is message.po for Spanish).

**Comment by ThiefMaster** [comment]
The Python error seems to be safe to ignore when just using the docker commands. And it looks like our docker dev build does not build the locales, so if you do not have them in your working copy (en is not under version control since it's autogenerated from the source file), he build fails..

**Comment by yarons** [comment]
I understand why it happens but it shouldn't happen since I only ran the development command, it should build the messages.po file along with docker, am I right?

BTW I think it should be implemented in a different way, it would be better to generate a POT file and then generate an English messages.po file from it, this method will allow updating the rest of the languages when needed and it will also allow using a localization platform.

**Comment by ThiefMaster** [comment]
I agree, a pot file would be much nicer. In the meantime the [contribution](https://github.com/lingui/js-lingui/pull/814) i made to the library we use to add support for generating a pot file was merged so some day I'll look into doing that :)

**Comment by yarons** [comment]
Ohhh that's wondeful :)

I would love to help with a localization platform if you wish.

Regarding generating the messages.po file for English during Docker building, what do you think we should do to solve this issue? It's related to localization but affecting the whole project sadly.

**Comment by ThiefMaster** [comment]
> I would love to help with a localization platform if you wish.

We have one ;) https://hosted.weblate.org/projects/newdle/client/

> So we already know what's going on with generating the po file, anything I can help with?

I think I found the problem: We extract the i18n stuff when building a production-like bundle in the builder image, but in `make docker-dev-run` we no longer have those files since we're mounting the local source trees as a volume..

I think running `make i118n` in the entrypoint of the `react-server` container of the dev compose file would help (make sure to be in the correct location though, since we're setting a `working_dir` there.

Do you want to have a look and maybe send a PR to fix it?

**Comment by yarons** [comment]
Hmmm I'm trying to add it but it looks like the Makefile is out of scope for us.
The mount is `'./newdle/client:/newdle/client'` while the Makefile is in a completely different location, is there a way for me to add it to the mounting (it may cause some redundancy or loops) or shoudl I just run the command from the Makefile manually instead of a make target?

BTW Hebrew translation is done, now I'll also have to open an additional bug on adjusting the CSS to support RTL (Right-To-Left).

**Comment by ThiefMaster** [comment]
You're right, I didn't notice we aren't mounting anything that's not the client in there. `npm run extract` and `npm run compile` should work though. In the end the Makefile just calls that.

**Comment by yarons** [comment]
The PR is on its way :)
Hoping to see the Hebrew translation and the RTL CSS soon as well :)
Thank you!
