### ISSUE TITLE
encoded &nbsp; leads to an API error

### ISSUE THREAD

**Issue by avivace** [indico/newdle#363]
I noticed a strange interaction between indico and newdle links,I don't know how to reproduce it but it already happened a couple of times (from minutes added by others):

When you add a link in a list in the Indico, sometimes it adds a `&nbsp`, leading to the link having the UTF-8 encoding of this entity at the end of the href , resulting in the generated link being `https://newdle.cern.ch/newdle/NEWDLE_ID/summary%C2%A0`. When this happens, opening the newdle will result in a API error

```
Error: Request to /api/newdle/NEWDLE_ID/participants/summary%C2%A0 failed (404): Specified participant does not exist
```

**Comment by ThiefMaster** [comment]
I'm not sure there's something to fix there.. if the participant code is invalid, this error shows up. Only `summary` is special-cased to not be a participant code.

My guess would be someone accidentally added this nbsp to the URL on Indico, so the link should be fixed.
If you DM me the Indico link where this is the case on Mattermost I can have a look if that's indeed the case.
