### ISSUE TITLE
Make it less likely for people to share their personal participant link

### ISSUE THREAD

**Issue by ThiefMaster** [indico/newdle#378]
We had another case where someone sent that link to other people and was then surprised that they were answering on his behalf.

Some ideas:

- When you're the newdle creator (or generally when viewing the summary?), clearly display the main newdle link for sharing - currently we only show it right after creation and then never again, so of course people end up copying URLs from the address bar
- On the participant view, when there's a participant token in the URL, show a warning somewhere that the page is personal, and maybe that they can get a link to share / invite someone else to submit (clicking there would then copy the shareable link without the participant token).

**Comment by TimSmithCH** [comment]
Both ideas LGTM. The failure mode for this case was after failing to agree on a slot, he edited the Newdle to add more slots and then wanted to alert everyone again. So the sharing URL should be also visible after saving a new edit
