### ISSUE TITLE
Export Newdle results in an Excel file

### ISSUE THREAD

**Issue by mosselmans** [indico/newdle#399]
Would be nice to download the results of the Newdle in an Excel file for further processing.
My use case : I need to find 2 dates for the same training, and want to maximize the attendance.
So I need to be able to see which combination of dates gives the best results.

**Comment by tgershon** [comment]
+1 for this (even though it appears a fix is already in the pipeline).  another use case: of the people who filled the newdle, some are essential for the meeting, some are important, some are useful.  if I can export the data I can optimise the attendance by adding corresponding weights.
