### ISSUE TITLE
Make it easier to create timeslots

### ISSUE THREAD

**Issue by tomasr8** [indico/newdle#490]
Currently, to create a time slot one must use the time picker which is not very efficient when you need to create
lots of time slots. Indico's Room Booking allows you to to drag your mouse to create a booking:

![image](https://github.com/user-attachments/assets/0505b746-d92b-4e76-8657-b22e64b8b9be)

I think it'd be great if we had something like this in Newdle to be able to quickly create time slots.

**Comment by renefs** [comment]
I'm thinking if this would be the best possible approach. Let me explain. In the new newdle page, there is a predefined slot duration (30 minutes, 1 hour, etc). With a mouse drag, you could select whatever slot duration you want, several times in a day. Is this practical when the default behavior is to have several slots of the same duration?.

What about just clicking on the desired time, and adding one slot with the specified default duration to the timeline? This can be done multiple times (multiple clicks, without the need of the opening the input) and the time of each new newdle would always be the same :)

**Comment by tomasr8** [comment]
Good point, we don't actually need the drag part since the duration is given

**Comment by renefs** [comment]
There are still some things to improve, but let me know if I'm on the right direction.

https://github.com/user-attachments/assets/6c3e435c-fd96-4fcc-b54c-1ec05d866654

**Comment by tomasr8** [comment]
Yeah I'd go with 15 min steps, if you need more granularity you can always use the time picker.
Also, I wonder if it'd make sense to render the timeslot block (maybe with a lower opacity and/or a different color) when you're just hovering with the mouse and not only after clicking?

**Comment by manwegit** [comment]
Definitely a welcomed feature to be able to just click the timeslot.
