### ISSUE TITLE
Style time slots a bit better

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#51]
* Show clearly that two adjacent slots are not connected;
 * Show start/end times on hover.

**Comment by panagiotappl** [comment]
I think the first bullet point is covered: 
![adjacent](https://user-images.githubusercontent.com/17234430/64864837-3f4c7a00-d638-11e9-8253-ba49f34ce3fa.png)

**Comment by ThiefMaster** [comment]
> Right now, I can add a time slot at 4 am even though it's not visible.

I think it'd be nicer if we automatically adjusted the view if someone adds a timeslot outside the usual range.
