### ISSUE TITLE
Reset Newdle creation

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#52]
Right now it's impossible to reset the current state data without either creating a newdle or reloading the page. If the user wants to start from scratch, they should be able to.
An option could be to add some 'beforeunload' logic that triggers also whenever someone tries to access `/`.

**Comment by ThiefMaster** [comment]
https://github.com/indico/indico/blob/master/indico/web/client/js/react/forms/unload.jsx can probably be reused. Ideally we only enable it once something is in the state (so going to creation and leaving without any changes doesn't trigger it)
