### ISSUE TITLE
Improve "change xxxx" options in last step

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#64]
They currently look like this:

![image](https://user-images.githubusercontent.com/2699/65679570-a107dd80-e055-11e9-85c4-5567936957e7.png)

I think it's not very readable and we could probably come up with something better. One option would be two buttons, one with a one-arrow icon and the other one with a "fast" forward double-arrow icon.
I also think that making step indicators clickable would help a great deal with UX.

![image](https://user-images.githubusercontent.com/2699/65679596-a8c78200-e055-11e9-830c-a53eeff0ab97.png)

**Comment by ThiefMaster** [comment]
I think actual buttons look a bit too prominent (that's why I suggested using links for it) - I guess you don't have to go back that often.

**Comment by pferreir** [comment]
We have buttons that take you to the next step. They're normally located on the right side of the screen. This screen kind of breaks with the whole logic.

**Comment by pferreir** [comment]
Plus in step 2 we have this:

![image](https://user-images.githubusercontent.com/2699/65679738-fc39d000-e055-11e9-9f41-571c08429e32.png)
