### ISSUE TITLE
CERN user directory integration

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#89]

**Comment by ThiefMaster** [comment]
...which isn't actually using LDAP ;)

**Comment by pferreir** [comment]
> ...which isn't actually using LDAP ;)

Indeed. Is it something specific to OpenID connect? Or just CERN-specific?

**Comment by ThiefMaster** [comment]
that API is completely cern-specific :/ at some point we probably need to split this into a separate package or something to keep the newdle core generic..

**Comment by pferreir** [comment]
Indeed.
