### ISSUE TITLE
Show participant name when opening answer URL

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#96]
When I open the URL of an answer form I should get my name somewhere, so that it's clear that this is my answer page.

**Comment by ThiefMaster** [comment]
Indeed, probably in a similar place where we show the "tell us who you are" in case of an anonymous submission.

This is also useful if you are logged in as someone else for whatever reason

**Comment by pferreir** [comment]
I felt tempted about doing it in #94, but it was already getting too long of a PR.
