### ISSUE TITLE
Better answer editing UI

### ISSUE THREAD

**Issue by pferreir** [indico/newdle#97]
It's already possible to edit an answer by knowing its URL. However, the UI is not very clear.
I suspect, however, that we will need some way of figuring out whether it is the first time the user is answering that particular newdle, so that we can show the button as "Save answer" or "Submit answer", for instance. Rather than adding yet another column to the `Participant` model, we could just check whether `answers` is empty. Opinions?

**Comment by ThiefMaster** [comment]
Yes, empty answers is the correct way to check. BTW, we should make sure that we are sending an answer (even if it's "unavailable") for every time slot when saving, so you don't have an empty list of answers in that case.
